// Deffence global state
int DGS[8];

// Registration variables for Europe nations AI

// millitary unit upgrades
GAMEOBJ MUSHCOST;
GAMEOBJ GRENPIKA1;
GAMEOBJ GRENPIKA2;
GAMEOBJ GRENPIKA3;

// stable
GAMEOBJ DRAGUN17;
GAMEOBJ DRAGUN17_UA0;
GAMEOBJ DRAGUN17_UA1;
GAMEOBJ DRAGUN17_UA2;
GAMEOBJ DRAGUN17_UA3;
GAMEOBJ DRAGUN17_UA4;
GAMEOBJ DRAGUN17_UA5;
GAMEOBJ DRAGUN17_US0;
GAMEOBJ DRAGUN17_US1;
GAMEOBJ DRAGUN17_US2;
GAMEOBJ DRAGUN17_US3;
GAMEOBJ DRAGUN17_US4;
GAMEOBJ DRAGUN17_US5;

GAMEOBJ DRAGUN18;
GAMEOBJ DRAGUN18_UA0;
GAMEOBJ DRAGUN18_UA1;
GAMEOBJ DRAGUN18_UA2;
GAMEOBJ DRAGUN18_UA3;
GAMEOBJ DRAGUN18_UA4;
GAMEOBJ DRAGUN18_UA5;
GAMEOBJ DRAGUN18_US0;
GAMEOBJ DRAGUN18_US1;
GAMEOBJ DRAGUN18_US2;
GAMEOBJ DRAGUN18_US3;
GAMEOBJ DRAGUN18_US4;
GAMEOBJ DRAGUN18_US5;



//---------------------------------------------------------------//
//                           1. Units                            //
//---------------------------------------------------------------//
GAMEOBJ OFFICER;
GAMEOBJ BARABAN;
GAMEOBJ INFANTRY;
GAMEOBJ PEASANT;
GAMEOBJ GRENDIP;
GAMEOBJ STREL17;
GAMEOBJ RICAR;
GAMEOBJ KIRASIR;
GAMEOBJ GREN18;
GAMEOBJ PUSHKA;
GAMEOBJ PUSHKA17;
GAMEOBJ GAUB;
GAMEOBJ MORTIRA;
GAMEOBJ MORTIRA17;
GAMEOBJ FASTUNIT;
GAMEOBJ KAZAK;
GAMEOBJ ARCHER;
GAMEOBJ DIPDRAGUN;
// church
GAMEOBJ PRIEST;
//-----------------------------SHEEPS----------------------------//
GAMEOBJ LODKA;
GAMEOBJ FREGAT;
GAMEOBJ GALLEY;
GAMEOBJ YAHTA;
GAMEOBJ LINKOR;
GAMEOBJ PAROM;
//-----------------------------TOWERS----------------------------//
GAMEOBJ TOWERUP1;
GAMEOBJ TOWERUP2;
GAMEOBJ TOWERUP3;
GAMEOBJ TOWERUP4;
GAMEOBJ TOWERUP5;
GAMEOBJ TOWERUP6;

//2.Buildings

GAMEOBJ CENTER;
GAMEOBJ MELN;
GAMEOBJ KAZ17;
GAMEOBJ KAZ18;
GAMEOBJ SKLAD;
GAMEOBJ AKADEMIA;
GAMEOBJ STABLE;
GAMEOBJ DIPCENTER;
GAMEOBJ ARTDEPO;
GAMEOBJ RINOK;
GAMEOBJ TOWER;
GAMEOBJ KUZNICA;
GAMEOBJ CHURCH;
GAMEOBJ PORT;

//3.Upgrades

GAMEOBJ OFFATTACK;
GAMEOBJ OFFSHIELD;
GAMEOBJ BARSHIELD;

GAMEOBJ INFANTRY_UA0;
GAMEOBJ INFANTRY_UA1;
GAMEOBJ INFANTRY_UA2;
GAMEOBJ INFANTRY_UA3;
GAMEOBJ INFANTRY_UA4;
GAMEOBJ INFANTRY_US0;
GAMEOBJ INFANTRY_US1;
GAMEOBJ INFANTRY_US2;
GAMEOBJ INFANTRY_US3;
GAMEOBJ INFANTRY_US4;

GAMEOBJ SINFANTRY_UA0;
GAMEOBJ SINFANTRY_UA1;
GAMEOBJ SINFANTRY_UA2;
GAMEOBJ SINFANTRY_US0;
GAMEOBJ SINFANTRY_US1;
GAMEOBJ SINFANTRY_US2;

GAMEOBJ STREL17_UA0;
GAMEOBJ STREL17_UA1;
GAMEOBJ STREL17_UA2;
GAMEOBJ STREL17_US0;
GAMEOBJ STREL17_US1;
GAMEOBJ STREL17_US2;
GAMEOBJ STREL17_US3;

GAMEOBJ RICAR_UA0;
GAMEOBJ RICAR_UA1;
GAMEOBJ RICAR_UA2;
GAMEOBJ RICAR_UA3;
GAMEOBJ RICAR_UA4;
GAMEOBJ RICAR_UA5;
GAMEOBJ RICAR_US0;
GAMEOBJ RICAR_US1;
GAMEOBJ RICAR_US2;
GAMEOBJ RICAR_US3;
GAMEOBJ RICAR_US4;
GAMEOBJ RICAR_US5;

GAMEOBJ KIRASIR_UA0;
GAMEOBJ KIRASIR_UA1;
GAMEOBJ KIRASIR_UA2;
GAMEOBJ KIRASIR_UA3;
GAMEOBJ KIRASIR_UA4;
GAMEOBJ KIRASIR_UA5;
GAMEOBJ KIRASIR_US0;
GAMEOBJ KIRASIR_US1;
GAMEOBJ KIRASIR_US2;
GAMEOBJ KIRASIR_US3;
GAMEOBJ KIRASIR_US4;
GAMEOBJ KIRASIR_US5;

GAMEOBJ GREN18_UA0;
GAMEOBJ GREN18_UA1;
GAMEOBJ GREN18_UA2;
GAMEOBJ GREN18_UA3;
GAMEOBJ GREN18_UA4;
GAMEOBJ GREN18_UA5;
GAMEOBJ GREN18_US0;
GAMEOBJ GREN18_US1;
GAMEOBJ GREN18_US2;
GAMEOBJ GREN18_US3;
GAMEOBJ GREN18_US4;
GAMEOBJ GREN18_US5;

GAMEOBJ PUSHKA_UB0;
GAMEOBJ PUSHKA_UB1;
GAMEOBJ PUSHKA_UB2;
GAMEOBJ PUSHKA_UB3;
GAMEOBJ PUSHKA_UB4;

GAMEOBJ GAUB_UB0;
GAMEOBJ GAUB_UB1;
GAMEOBJ GAUB_UB2;
GAMEOBJ GAUB_UB3;

GAMEOBJ MELN_U;
GAMEOBJ MELN_U1;
GAMEOBJ KUZ_FIELD;
GAMEOBJ AKAFOOD1;
GAMEOBJ AKAFOOD2;
GAMEOBJ AKAFOOD3;
GAMEOBJ AKAFOOD4;
GAMEOBJ AKAWOOD;
GAMEOBJ AKASTN1;
GAMEOBJ AKASTN2;

GAMEOBJ XVIII;
GAMEOBJ FASTHORSE;
GAMEOBJ AKASBUIL;

GAMEOBJ ATTPAUS1;
GAMEOBJ ATTPAUS2;
GAMEOBJ AKASTR1;
GAMEOBJ AKASTR2;
GAMEOBJ AKASTR3;
GAMEOBJ AKASTR4;

GAMEOBJ AKASWALL;
GAMEOBJ B_SHIELD1;
GAMEOBJ B_SHIELD2;

GAMEOBJ AKARAZBROS;

GAMEOBJ FLOT;
GAMEOBJ FASTFLOT;
GAMEOBJ DOLINKOR;
GAMEOBJ ENABLE_FREGAT;
GAMEOBJ CHIPFISH;
GAMEOBJ FASTFISH;

GAMEOBJ STRONGPIKA;//KUZ05
GAMEOBJ STRONGSHIELD;//KUZ06
GAMEOBJ AKASHIELD;//AKA34
GAMEOBJ AKAMUSKETCOST; //AKA32
GAMEOBJ EN_FREG18;
GAMEOBJ EN_KETC18;
GAMEOBJ KETC18;
GAMEOBJ FREG18;

